name: letaoyuan_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test: 
    sdk: flutter
  get: ^4.6.5
  dio: ^4.0.6
  quiver: ^3.1.0
  nb_utils: ^4.6.23
  flutter_screenutil: ^5.5.3+2
  flutter_easyrefresh: ^2.2.1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.0.15
  device_info_plus: ^4.0.0
  package_info_plus: ^1.4.2
  #kooboo_flutter_app_upgrade: ^0.0.9
  google_sign_in: ^5.3.3
  #sign_in_with_apple: ^3.3.0
  flutter_login_facebook: ^1.4.1
  permission_handler: ^9.2.0
  wechat_assets_picker: ^7.3.2
  wechat_camera_picker: ^3.4.0
  flutter_image_compress: ^1.1.0
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0
  waterfall_flow: ^3.0.2
  webview_flutter: ^3.0.4
  photo_view: ^0.14.0
  flutter_html: ^3.0.0-alpha.5
  tuple: ^2.0.0
  fluwx: ^3.9.1
  flutter_app_badger: ^1.4.0
  image_gallery_saver: ^1.7.1
  android_id: ^0.0.7


flutter: 
  uses-material-design: true

